export const actionTypes = {
    SET_TITLE: 'SET_TITLE',
    SET_FIRST: 'SET_FIRST',
    SET_LAST: 'SET_LAST',
    SET_EMAIL: 'SET_EMAIL',
    SET_CELL: 'SET_CELL',
    SET_STREET: 'SET_STREET',
    SET_CITY: 'SET_CITY',
    SET_STATE: 'SET_STATE',
    SET_POSTCODE: 'SET_POSTCODE',
}